config/routes.rb
Lab8::Application.routes.draw do
  
  get "sessions/new"

  resources :users
  resources :sessions, :only => [:new, :create, :destroy]
  resources :ideas, :only => [:create, :destroy]
  resources :responses
  
  root :to => 'pages#home'
  
  
  match '/contact', :to => 'pages#contact'
  match '/about', :to => 'pages#about'
  match '/help', :to => 'pages#help'
 
  match '/signup', :to => 'users#new'
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
 
 

end

app/views/layouts/_header.html.erb
<div id="pageheader">
	
<div id="pageheadertitle">
	<a href="http://localhost:3000">
We The Students
</a>
</div>

<div id="loginbox">
	
	<% if signed_in? %>
	
  

   <%= link_to "Sign out", signout_path, :method => :delete%>

	<%else%>
<%= link_to "Sign in", signin_path%>

<%end%>
</div>

</div>

app/views/layouts/_nav.html.erb
<div id="frame">
<div id="Navheader"><br>
	<% if signed_in? %>

<span id="JumpList"><%= link_to "Ideas i've posted", user_path(current_user)%></span>

<span id="JumpList"><%= link_to "Settings", edit_user_path(current_user)%></span>
<span id="JumpList"><%= link_to "Other Students", users_path%></span>
<%end%>
<span id="JumpList"> <%= link_to "help", help_path%></span>
<% if signed_in? %>
<span id="JumpList"><%= render 'shared/user_info' %></span>

        
<%end%>
</div>

app/views/layouts/_tail.html.erb
</div>
</div>
</div>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= @title %></title>

<%= stylesheet_link_tag    'AWMlab7', :media => 'screen' %>
<%= javascript_include_tag :defaults %>


  
</head>
<body>
<%= render 'layouts/header'%>
<%= render 'layouts/nav'%>
<section class"round">
<% flash.each do |key, value|%>
<div class="flash <%= key %>"><%= value %></div>
<%end%>
</section>
<%= yield %>
<%= render 'layouts/tail'%>
<%= debug(params) if Rails.env.development? %>